services:
    dynamodb:
        image: amazon/dynamodb-local
        container_name: dynamodb
        ports:
            - 8000:8000
        command: -jar DynamoDBLocal.jar -dbPath /data -sharedDb
        volumes:
            - $PWD/dynamodb/data:/data

    dynamodb-admin:
        container_name: dynamodb-admin
        image: aaronshaf/dynamodb-admin:latest
        environment:
            - DYNAMO_ENDPOINT=dynamodb:8000
        ports:
            - 8001:8001
        depends_on:
            - dynamodb

    sveltekit:
        build:
            context: .
            dockerfile: Dockerfile.Svelte
        ports:
            - '5177:5173'
        volumes:
            - .:/app
            - /app/node_modules
        environment:
            NODE_ENV: development
        depends_on:
            - dynamodb

    awscli:
        # dynamodbが起動していることを確認してから起動
        depends_on:
            - dynamodb
        # awscli-local イメージを使用する
        image: amazon/aws-cli
        container_name: awscli-local
        volumes:
            - $PWD/dynamodb:/dynamodb
        ports:
            - '8089:8080'
        # entrypoint: エントリーポイントは空
        entrypoint: ['']
        # tty: true: ターミナルを使う
        tty: true
        # ACCESS_KEY_IDとSECRET_ACCESS_KEYはローカル接続なので適当
        environment:
            AWS_DEFAULT_REGION: ap-northeast-1
            AWS_ACCESS_KEY_ID: 'DUMMY'
            AWS_SECRET_ACCESS_KEY: 'DUMMY'
        # シェルを実行
        command:
            - /bin/sh

    minio:
        image: minio/minio
        ports:
            - 9000:9000 # S3-compatible API
            - 9001:9001 # Web Console
        volumes:
            - $PWD/dynamodb:/dynamodb
        environment:
            - MINIO_ROOT_USER=minioadmin
            - MINIO_ROOT_PASSWORD=minioadmin
        command: server --console-address ":9001" /data
        healthcheck:
            test: ['CMD', 'mc', 'ready', 'local']
            interval: 5s
            timeout: 5s
            retries: 5
