version: '3'

services:
  bridge_eqsimu_lambda_dev:
    container_name: dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ~/.aws/credentials:/root/.aws/credentials:ro
      - ~/.aws/config:/root/.aws/config:ro
      - ./src:/app/src
    ports:
      - "8000:8000"
    environment:
      PYTHONPATH: "/app"
    command: ["poetry", "run", "uvicorn", "src.server:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
