FROM python:3.11

WORKDIR /app

RUN apt-get update &&\
    apt-get -y install locales &&\
    localedef -f UTF-8 -i ja_JP ja_JP.UTF-8
ENV LANG ja_JP.UTF-8
ENV LANGUAGE ja_JP:ja
ENV LC_ALL ja_JP.UTF-8
ENV TZ JST-9
ENV TERM xterm

RUN pip install --upgrade pip

# Copy function code and runtime dependencies from the build stage
RUN pip install poetry \
    && poetry config virtualenvs.create false

COPY ./.env /app
COPY ./pyproject.toml ./poetry.lock* /app

# export requirements.txt from poetry pyproject.toml.
RUN poetry export --without-hashes --output requirements.txt

# Install the specified packages
RUN pip3 install -r requirements.txt

RUN poetry install
