version: '3'

services:
  bridge_eqsimu_lambda_prod:
    image: bridge_eqsim_backend_ecr:latest
    container_name: prod
    build: .
    volumes:
      - ./src:/app/src
    ports:
      - "9000:8080"
    environment:
      PYTHONPATH: "/app"
